const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function payload(){const ids=['brand','model','board','fault','history','symptoms','current','dcps_voltage','battery_voltage','usb_current','current_profile','resistance','resistance_location','diode','diode_location','rail','thermal','visual','repair_history','known_good','extra'];const o={};ids.forEach(k=>o[k]=$(k)?.value?.trim()||'');return o}
function render(d){const hs=d.hypotheses||[];$('result').innerHTML=`<div class="result-head"><div><h2>نتيجة Matrex Pro</h2><span class="pill">Engine ${esc(d.engine_version)}</span></div><div class="confidence">${esc(d.confidence)}%</div></div><p class="muted">${esc(d.fault_label)} · ثقة إرشادية وليست احتمالًا إحصائيًا.</p><p class="danger">${esc(d.disclaimer)}</p><h3>الاحتمالات المرتبة</h3>${hs.map((x,i)=>`<div class="hyp"><div><b>${esc(x.rank)}. ${esc(x.name)}</b><span class="pill" style="float:left">${esc(x.score)}% وزن</span></div><div class="bar"><i style="width:${Math.min(100,x.score)}%"></i></div></div>`).join('')||'<p class="muted">لا توجد فرضيات كافية.</p>'}<h3>الأدلة التي تم استخدامها</h3>${(d.evidence||[]).map(x=>`<div class="evidence">${esc(x)}</div>`).join('')||'<div class="warning">لم تدخل قياسات كافية.</div>'}<h3>التناقضات / حدود الاستنتاج</h3>${(d.contradictions||[]).map(x=>`<div class="warning">${esc(x)}</div>`).join('')||'<p class="muted">لا توجد تناقضات واضحة في البيانات المدخلة.</p>'}<h3>القياس التالي الأكثر فائدة</h3>${(d.next_steps||[]).map((x,i)=>`<div class="next"><b>${i===0?'الأولوية 1':i+1+'.'}</b> ${esc(x)}</div>`).join('')}<h3>منهج التحليل</h3><p class="muted">${(d.method||[]).map(esc).join(' → ')}</p><div class="actions"><button class="btn primary" id="save">حفظ الحالة والتقرير</button><button class="btn" id="copy">نسخ التقرير</button></div>`;$('save').onclick=save;$('copy').onclick=()=>copyReport(d)}
async function analyze(){const r=$('result');r.innerHTML='<h2>جاري التحليل…</h2><p class="muted">يتم فحص نمط السحب والقياسات والتناقضات ثم اختيار القياس التالي.</p>';try{const res=await fetch('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload())});const d=await res.json();if(!res.ok)throw Error(d.error||'API error');localStorage.setItem('matrex_last_case',JSON.stringify(payload()));localStorage.setItem('matrex_last_result',JSON.stringify(d));render(d)}catch(e){r.innerHTML=`<h2>تعذر التحليل</h2><p class="danger">${esc(e.message)}</p><p class="muted">تحقق من اتصال الإنترنت والخادم ثم أعد المحاولة.</p>`}}
async function save(){try{const res=await fetch('/api/cases',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload())});const d=await res.json();alert(res.ok?`تم حفظ الحالة رقم ${d.id}`:'فشل حفظ الحالة')}catch{alert('تعذر حفظ الحالة')}}
function copyReport(d){const p=payload();const text=['MATREX PRO',`Device: ${p.brand} ${p.model}`,`Fault: ${d.fault_label}`,`Confidence: ${d.confidence}%`,'Hypotheses:',...(d.hypotheses||[]).map(x=>`${x.rank}. ${x.name} — ${x.score}%`),'Evidence:',...(d.evidence||[]).map(x=>`- ${x}`),'Contradictions:',...(d.contradictions||[]).map(x=>`- ${x}`),'Next steps:',...(d.next_steps||[]).map((x,i)=>`${i+1}. ${x}`)].join('\n');navigator.clipboard?.writeText(text);alert('تم نسخ التقرير')}
function fillDemo(){const v={brand:'Apple',model:'iPhone 13',board:'A2633 / unknown revision',fault:'no_power',history:'سقوط ثم توقف عن العمل',symptoms:'لا يستجيب لزر التشغيل ولا توجد صورة',current:'0A → 0.08A → 0A',dcps_voltage:'4.2V',battery_voltage:'3.85V',usb_current:'',current_profile:'80mA لمدة أقل من ثانية ثم يعود للصفر',resistance:'1.2 Ω',resistance_location:'PP_VDD_MAIN',diode:'0.31V',diode_location:'PP_VDD_MAIN / Red-GND',rail:'PP_VDD_MAIN=4.2V',thermal:'لا توجد حرارة واضحة',visual:'لا يوجد كسر واضح',repair_history:'لا توجد صيانة سابقة',known_good:'غير متوفر',extra:''};Object.entries(v).forEach(([k,val])=>{if($(k))$(k).value=val})}
function clearForm(){$('case').reset();$('result').innerHTML='<div class="result-head"><h2>جاهز للتحليل</h2><span class="pill">Matrex Pro</span></div><p class="muted">أدخل ما لديك من بيانات.</p>'}
$('case').addEventListener('submit',e=>{e.preventDefault();analyze()});$('demo').onclick=fillDemo;$('clear').onclick=clearForm;
